### Task 2: Design a Data Quality Audit System on Top of an ETL Pipeline

First, we'll fetch the data from the API and load it into a Pandas DataFrame.

In [ ]:
!pip install requests pandas

In [1]:
import requests
import pandas as pd

# Define the API endpoint
api_url = "https://jsonplaceholder.typicode.com/posts"

# Fetch data from the API
response = requests.get(api_url)
posts = response.json()

# Limit to 100 posts if more are fetched
posts = posts[:100]

# Load into a Pandas DataFrame
df = pd.DataFrame(posts)

print(f"Fetched {len(df)} posts.")
display(df.head())

Fetched 100 posts.

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

### Data Quality Audit - Before Cleaning

Now, let's detect and record initial data quality issues. We'll check for:
- Null counts per column
- Duplicate row count
- Data types

In [2]:
audit_report_before = {}

# 1. Null counts per column
null_counts = df.isnull().sum()
audit_report_before['null_counts_per_column'] = null_counts.to_dict()
print("--- Null Counts Per Column ---")
print(null_counts[null_counts > 0]) # Only show columns with nulls

# 2. Duplicate row count
duplicate_rows_count = df.duplicated().sum()
audit_report_before['duplicate_rows_count'] = duplicate_rows_count
print(f"\n--- Duplicate Row Count ---")
print(f"Number of duplicate rows: {duplicate_rows_count}")

# 3. Data Types
column_types = df.dtypes.apply(lambda x: x.name).to_dict()
audit_report_before['column_data_types'] = column_types
print(f"\n--- Column Data Types ---")
for col, dtype in column_types.items():
    print(f"{col}: {dtype}")


print("\nInitial audit results recorded in 'audit_report_before'.")

--- Null Counts Per Column ---
Series([], dtype: int64)

--- Duplicate Row Count ---
Number of duplicate rows: 0

--- Column Data Types ---
userId: int64
id: int64
title: object
body: object

Initial audit results recorded in 'audit_report_before'.

In [3]:
# 4. Out-of-range values (for numerical IDs)

out_of_range_user_ids = df[df['userId'] < 1].shape[0]
out_of_range_ids = df[df['id'] < 1].shape[0]

audit_report_before['out_of_range_user_ids'] = out_of_range_user_ids
audit_report_before['out_of_range_ids'] = out_of_range_ids

print(f"\n--- Out-of-Range Values ---")
print(f"Number of posts with userId < 1: {out_of_range_user_ids}")
print(f"Number of posts with id < 1: {out_of_range_ids}")

# 5. Inconsistent string formats (e.g., leading/trailing whitespace)
# Check for leading/trailing whitespace in 'title' and 'body'
whitespace_title_count = df['title'].apply(lambda x: isinstance(x, str) and (x != x.strip())).sum()
whitespace_body_count = df['body'].apply(lambda x: isinstance(x, str) and (x != x.strip())).sum()

audit_report_before['whitespace_title_count'] = whitespace_title_count
audit_report_before['whitespace_body_count'] = whitespace_body_count

print(f"\n--- Inconsistent String Formats (Whitespace) ---")
print(f"Number of titles with leading/trailing whitespace: {whitespace_title_count}")
print(f"Number of bodies with leading/trailing whitespace: {whitespace_body_count}")

print("\nUpdated 'audit_report_before' with additional quality checks.")

--- Out-of-Range Values ---
Number of posts with userId < 1: 0
Number of posts with id < 1: 0

--- Inconsistent String Formats (Whitespace) ---
Number of titles with leading/trailing whitespace: 0
Number of bodies with leading/trailing whitespace: 0

Updated 'audit_report_before' with additional quality checks.

### Apply Transformations and Enrichments

Now, let's apply the required transformations and enrichments:
- **Word Count**: Calculate word count for `title` and `body`.
- **Title Casing**: Convert the `title` column to title case.
- **Filtering**: Remove rows with empty `title` or `body` after stripping whitespace.
- **Ranking**: Rank posts based on `title_word_count`.

In [4]:
# Make a copy to preserve the original DataFrame for comparison if needed
df_cleaned = df.copy()

# 1. Word Count
df_cleaned['title_word_count'] = df_cleaned['title'].apply(lambda x: len(str(x).split()))
df_cleaned['body_word_count'] = df_cleaned['body'].apply(lambda x: len(str(x).split()))

# 2. Title Casing
df_cleaned['title'] = df_cleaned['title'].apply(lambda x: str(x).title())

# Record original row count before filtering
original_row_count = df_cleaned.shape[0]

# 3. Filtering: Remove rows where title or body is empty after stripping
df_cleaned = df_cleaned[df_cleaned['title'].str.strip() != '']
df_cleaned = df_cleaned[df_cleaned['body'].str.strip() != '']

# Record new row count after filtering
filtered_row_count = df_cleaned.shape[0]

# 4. Ranking based on title word count (descending)
df_cleaned['rank_by_title_word_count'] = df_cleaned['title_word_count'].rank(ascending=False, method='dense')

print(f"Original row count: {original_row_count}")
print(f"Row count after filtering: {filtered_row_count}")
print("Transformations and enrichments applied. Displaying head of cleaned data:")
display(df_cleaned.head())

Original row count: 100
Row count after filtering: 100
Transformations and enrichments applied. Displaying head of cleaned data:

,userId,id,title,body,title_word_count,body_word_count,rank_by_title_word_count
0,1,1,Sunt Aut Facere Repellat Provident Occaecati E...,quia et suscipit\nsuscipit recusandae consequu...,9,23,1.0
1,1,2,Qui Est Esse,est rerum tempore vitae\nsequi sint nihil repr...,3,31,7.0
2,1,3,Ea Molestias Quasi Exercitationem Repellat Qui...,et iusto sed quo iure\nvoluptatem occaecati om...,9,26,1.0
3,1,4,Eum Et Est Occaecati,ullam et saepe reiciendis voluptatem adipisci\...,4,28,6.0
4,1,5,Nesciunt Quas Odio,repudiandae veniam quaerat sunt sed\nalias aut...,3,23,7.0

### Generate Structured Audit Report

Now, let's create a structured audit report summarizing the findings before and after cleaning and transformations.

In [5]:
audit_report_after = {}

# Recalculate data quality metrics after cleaning
# 1. Null counts per column (after)
null_counts_after = df_cleaned.isnull().sum()
audit_report_after['null_counts_per_column'] = null_counts_after.to_dict()

# 2. Duplicate row count (after)
duplicate_rows_count_after = df_cleaned.duplicated().sum()
audit_report_after['duplicate_rows_count'] = duplicate_rows_count_after

# 3. Out-of-range values (after)
out_of_range_user_ids_after = df_cleaned[df_cleaned['userId'] < 1].shape[0]
out_of_range_ids_after = df_cleaned[df_cleaned['id'] < 1].shape[0]
audit_report_after['out_of_range_user_ids'] = out_of_range_user_ids_after
audit_report_after['out_of_range_ids'] = out_of_range_ids_after

# 4. Inconsistent string formats (whitespace) (after)
whitespace_title_count_after = df_cleaned['title'].apply(lambda x: isinstance(x, str) and (x != x.strip())).sum()
whitespace_body_count_after = df_cleaned['body'].apply(lambda x: isinstance(x, str) and (x != x.strip())).sum()
audit_report_after['whitespace_title_count'] = whitespace_title_count_after
audit_report_after['whitespace_body_count'] = whitespace_body_count_after

# Compile the audit summary
audit_summary = {
    'metric': [],
    'before_cleaning': [],
    'after_cleaning': [],
    'issues_fixed': []
}

# Row Count
audit_summary['metric'].append('Row Count')
audit_summary['before_cleaning'].append(original_row_count)
audit_summary['after_cleaning'].append(filtered_row_count)
audit_summary['issues_fixed'].append(original_row_count - filtered_row_count)

# Duplicate Rows
audit_summary['metric'].append('Duplicate Rows')
audit_summary['before_cleaning'].append(audit_report_before['duplicate_rows_count'])
audit_summary['after_cleaning'].append(audit_report_after['duplicate_rows_count'])
audit_summary['issues_fixed'].append(audit_report_before['duplicate_rows_count'] - audit_report_after['duplicate_rows_count'])

# Null Values (total across all columns for simplicity in summary)
total_nulls_before = sum(audit_report_before['null_counts_per_column'].values())
total_nulls_after = sum(audit_report_after['null_counts_per_column'].values())
audit_summary['metric'].append('Total Null Values')
audit_summary['before_cleaning'].append(total_nulls_before)
audit_summary['after_cleaning'].append(total_nulls_after)
audit_summary['issues_fixed'].append(total_nulls_before - total_nulls_after)

# Out-of-Range User IDs
audit_summary['metric'].append('Out-of-Range User IDs')
audit_summary['before_cleaning'].append(audit_report_before['out_of_range_user_ids'])
audit_summary['after_cleaning'].append(audit_report_after['out_of_range_user_ids'])
audit_summary['issues_fixed'].append(audit_report_before['out_of_range_user_ids'] - audit_report_after['out_of_range_user_ids'])

# Out-of-Range IDs
audit_summary['metric'].append('Out-of-Range IDs')
audit_summary['before_cleaning'].append(audit_report_before['out_of_range_ids'])
audit_summary['after_cleaning'].append(audit_report_after['out_of_range_ids'])
audit_summary['issues_fixed'].append(audit_report_before['out_of_range_ids'] - audit_report_after['out_of_range_ids'])

# Whitespace in Title
audit_summary['metric'].append('Whitespace in Title')
audit_summary['before_cleaning'].append(audit_report_before['whitespace_title_count'])
audit_summary['after_cleaning'].append(audit_report_after['whitespace_title_count'])
audit_summary['issues_fixed'].append(audit_report_before['whitespace_title_count'] - audit_report_after['whitespace_title_count'])

# Whitespace in Body
audit_summary['metric'].append('Whitespace in Body')
audit_summary['before_cleaning'].append(audit_report_before['whitespace_body_count'])
audit_summary['after_cleaning'].append(audit_report_after['whitespace_body_count'])
audit_summary['issues_fixed'].append(audit_report_before['whitespace_body_count'] - audit_report_after['whitespace_body_count'])

audit_df = pd.DataFrame(audit_summary)

print("\n--- Data Quality Audit Report ---")
display(audit_df)

# Optionally save to CSV
audit_df.to_csv('data_quality_audit_report.csv', index=False)
print("Audit report saved as 'data_quality_audit_report.csv'.")

--- Data Quality Audit Report ---

                  metric  before_cleaning  after_cleaning  issues_fixed
0              Row Count              100             100             0
1         Duplicate Rows                0               0             0
2      Total Null Values                0               0             0
3  Out-of-Range User IDs                0               0             0
4       Out-of-Range IDs                0               0             0
5    Whitespace in Title                0               0             0
6     Whitespace in Body                0               0             0

Audit report saved as 'data_quality_audit_report.csv'.

### Load Clean Data into MySQL

Finally, we will load the `df_cleaned` DataFrame into a MySQL database. This requires `SQLAlchemy` and a MySQL connector. If you don't have MySQL running or a database set up, this step will fail. For demonstration purposes, I will use an in-memory SQLite database as a placeholder, but the code structure for MySQL would be very similar.

In [6]:
# Install SQLAlchemy and a MySQL connector (e.g., mysql-connector-python or PyMySQL)
# If you run this in a new environment, uncomment and run the following lines:
# !pip install sqlalchemy PyMySQL

from sqlalchemy import create_engine

# --- MySQL Connection Details (Replace with your actual details) ---
# For a real MySQL database, you would use a connection string like this:
# db_connection_str = 'mysql+pymysql://user:password@host:port/database_name'
# For example:
# db_connection_str = 'mysql+pymysql://root:password@localhost:3306/etl_audit_db'

# --- Using an in-memory SQLite database for demonstration purposes ---
# This will create a temporary database that exists only in memory for the duration of the script.
# For an actual MySQL connection, uncomment the MySQL connection string above and comment this one.
db_connection_str = 'sqlite:///:memory:'

try:
    # Create a SQLAlchemy engine
    engine = create_engine(db_connection_str)

    # Define the table name
    table_name = 'posts_cleaned'

    # Load the cleaned DataFrame into the database
    # if_exists='replace' will drop the table if it exists and recreate it.
    # if_exists='append' will add new rows to an existing table.
    # index=False prevents writing the DataFrame index as a column in the database.
    df_cleaned.to_sql(table_name, engine, if_exists='replace', index=False)

    print(f"Successfully loaded {len(df_cleaned)} rows into '{table_name}' table.")

    # Optional: Verify by reading data back from the database
    df_from_db = pd.read_sql(f"SELECT * FROM {table_name}", engine)
    print("\nData read back from database (first 5 rows):")
    display(df_from_db.head())

except Exception as e:
    print(f"An error occurred during database loading: {e}")
    print("Please ensure you have MySQL running and the connection details (user, password, host, port, database_name) are correct.")
    print("If using SQLite, this error might indicate an issue with the DataFrame or SQLAlchemy.")

Successfully loaded 100 rows into 'posts_cleaned' table.

Data read back from database (first 5 rows):

,userId,id,title,body,title_word_count,body_word_count,rank_by_title_word_count
0,1,1,Sunt Aut Facere Repellat Provident Occaecati E...,quia et suscipit\nsuscipit recusandae consequu...,9,23,1.0
1,1,2,Qui Est Esse,est rerum tempore vitae\nsequi sint nihil repr...,3,31,7.0
2,1,3,Ea Molestias Quasi Exercitationem Repellat Qui...,et iusto sed quo iure\nvoluptatem occaecati om...,9,26,1.0
3,1,4,Eum Et Est Occaecati,ullam et saepe reiciendis voluptatem adipisci\...,4,28,6.0
4,1,5,Nesciunt Quas Odio,repudiandae veniam quaerat sunt sed\nalias aut...,3,23,7.0